# Generated by Django 2.2 on 2019-04-29 05:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 29, 5, 19, 7, 122263, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
